export enum Group {
    SITUATION_ISSUE_COUNTS = 1,
    SITUATION_PROGRESSION_CHARTS = 2,
    SITUATION_OTHER_CHARTS = 3,
    ACTORS_COUNTS = 4,
    ACTORS_PARTICIPATION_CHARTS = 5,
    ACTIVITY_RESULTS_COUNTS = 6,
    ACTIVITY_RESULTS_CHARTS = 7
}