/* All free solid fontawesome icons -> https://fontawesome.com/icons?d=gallery&s=solid&m=free */

import {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faBullseye,    
    faChartArea,
    faChartBar,
    faChartPie,
    faCheckCircle,
    faChevronDown,
    faChevronUp,
    faCircle,
    faCog,
    faColumns,
    faDotCircle,
    faEdit,
    faPen,
    faPlus,
    faQuestionCircle,
    faSearch,
    faStopwatch,
    faTable,
    faTachometerAlt,
    faTimesCircle,
    faTrash,
    faUser,
    faWifi,
    faWrench
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeSolidIcons = {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faBullseye,    
    faChartArea,
    faChartBar,
    faChartPie,
    faCheckCircle,
    faChevronDown,
    faChevronUp,
    faCircle,
    faCog,
    faColumns,
    faDotCircle,
    faEdit,
    faPen,
    faPlus,
    faQuestionCircle,
    faSearch,
    faStopwatch,
    faTable,
    faTachometerAlt,
    faTimesCircle,
    faTrash,
    faUser,
    faWifi,
    faWrench
};
