name: Build Docker Images

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]
    

jobs:
  build-flint-reporting-client:
    name: Build FLINT Reporting Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/client/
    steps:
      - uses: actions/checkout@v2
      - name: Build FLINT Reporting Client
        run: docker build . --file Dockerfile --tag flint_reporting.client


  build-accountabilities-microservice:
    name: Build FLINT Reporting Accountability Microservice
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/accountabilities/
  
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build accountabilities microservice 
        run: docker build . --file Dockerfile --tag flint_reporting.accountabilities

  build-vegetation-types-microservice:
    name: Build FLINT Reporting Vegetation Types Microservice
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/vegetation-types/
  
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build Vegetation Types microservice 
        run: docker build . --file Dockerfile --tag flint_reporting.vegetation-types

    
  build-vegetation-history-vegetation-types-microservice:
    name: Build FLINT Reporting Vegetation History Vegetation Types
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/vegetation-history-vegetation-types/
  
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build egetation History Vegetation Types microservice 
        run: docker build . --file Dockerfile --tag flint_reporting.vegetation-history-vegetation-types

  build-units-microservice:
    name: Build FLINT Reporting Units
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/units/
  
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build Units microservice 
        run: docker build . --file Dockerfile --tag flint_reporting.units

  build-unit-categories-microservice:
    name: Build FLINT Reporting Unit Categories
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/unit-categories/

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build Unit Categories microservice
        run: docker build . --file Dockerfile --tag flint_reporting.unit-categories

  build-tasks-microservice:
    name: Build FLINT Reporting Tasks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/tasks/

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build Tasks microservice
        run: docker build . --file Dockerfile --tag flint_reporting.tasks

  build-task-manager-microservice:
    name: Build FLINT Reporting Task Manager
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/task-manager/

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build Task Manager microservice
        run: docker build . --file Dockerfile --tag flint_reporting.task-manager

  build-reporting-variables-microservice:
    name: Build FLINT Reporting Variables microservice
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/reporting-variables/

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build Reporting Variables microservice
        run: docker build . --file Dockerfile --tag flint_reporting.reporting-variables

  build-reporting-tables-microservice:
    name: Build FLINT Reporting Tables
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/reporting-tables/

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build Reporting Tables microservice
        run: docker build . --file Dockerfile --tag flint_reporting.reporting-tables

  build-reporting-frameworks-microservice:
    name: Build FLINT Reporting Frameworks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/reporting-frameworks/

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build Reporting Frameworks microservice
        run: docker build . --file Dockerfile --tag flint_reporting.reporting-frameworks

  build-quantity-observations-microservice:
    name: Build FLINT Reporting Quantity Observations
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/quantity-observations/

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build Reporting Quantity Observations microservice
        run: docker build . --file Dockerfile --tag flint_reporting.quantity-observations

  build-pools-microservice:
    name: Build FLINT Reporting Pools
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/pools/

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build pools microservice
        run: docker build . --file Dockerfile --tag flint_reporting.pools

  build-party-types-microservice:
    name: Build FLINT Reporting Party Types
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/party-types/

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build pools microservice
        run: docker build . --file Dockerfile --tag flint_reporting.pools

  build-parties-microservice:
    name: Build FLINT Reporting Parties
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/parties/

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build pools microservice
        run: docker build . --file Dockerfile --tag flint_reporting.parties

  build-locations-microservice:
    name: Build FLINT Reporting Locations
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/locations/

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build pools microservice
        run: docker build . --file Dockerfile --tag flint_reporting.locations