name: Build Docker Images

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]
    

jobs:
  # Build FLINT Reporting Tool UI
  build-flint-reporting-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/client/
    steps:
      - uses: actions/checkout@v2
      - name: Build FLINT Reporting Client
        run: docker build . --file Dockerfile --tag flint_reporting.client

  build-accountabilities-microservice:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/accountabilities/
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
      - name: Build code
        run: bash build.sh

    
      - uses: actions/checkout@v1
      - name: Build accountabilities microservice 
      
        run: docker build . --file Dockerfile --tag flint_reporting.accountabilities


    
     