name: FLINT Reporting Docker Images CI/CD

on:
  schedule:
    - cron: "0 0 * * MON"

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]

  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  publish-reporting-tool-frontend:
    name: Publish Reporting Tool (client)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-client-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-client-
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/moja-global/flint_reporting.client

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./code/client/
          file: "./code/client/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # This ugly bit is necessary if you don't want your cache to grow forever
      # till it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  publish-microservice:
    name: Publish Reporting Tool Microservice
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        services:
          - accountabilities
          - accountability-rules
          - accountability-types
          - conversion-and-remaining-periods
          - cover-types
          - crf-tables
          - data-aggregator
          - data-processor
          - databases
          - dates
          - emission-types
          - flux-reporting-results
          - flux-types
          - fluxes-to-reporting-variables
          - land-use-categories
          - land-uses-flux-types-to-reporting-tables
          - land-uses-flux-types
          - locations
          - parties
          - party-types
          - pools
          - quantity-observations
          - reporting-frameworks
          - reporting-tables
          - reporting-variables
          - task-manager
          - tasks
          - unit-categories
          - units
          - vegetation-history-vegetation-types
          - vegetation-types
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.services }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.services }}-
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/moja-global/flint_reporting.${{ matrix.services }}

      - name: Build with Maven
        run: |
          cd ./code/services/${{ matrix.services }}/
          bash build.sh
      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./code/services/${{ matrix.services }}
          file: "./code/services/${{ matrix.services }}/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
