name: Build Docker Images

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]
    

jobs: 
  build-accountabilities-microservice: 
    defaults: 
      run: 
        working-directory: ./code/services/accountabilities/
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        uses: actions/setup-java@v2
        with: 
          distribution: temurin
          java-version: "17"
          run: "bash build.sh"
      - 
        name: "Build accountabilities microservice"
        run: "docker build . --file Dockerfile --tag flint_reporting.accountabilities"
        uses: actions/checkout@v2
  build-flint-reporting-client: 
    defaults: 
      run: 
        working-directory: ./code/client/
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Build FLINT Reporting Client"
        run: "docker build . --file Dockerfile --tag flint_reporting.client"


    
     