name: Build Docker Images

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]
    

jobs:
  build-flint-reporting-client:
    name: Build FLINT Reporting Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/client/
    steps:
      - uses: actions/checkout@v2
      - name: Build FLINT Reporting Client
        run: docker build . --file Dockerfile --tag flint_reporting.client


  build-accountabilities-microservice:
    name: Build FLINT Reporting Accountability Microservice
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/accountabilities/
  
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build accountabilities microservice 
        run: docker build . --file Dockerfile --tag flint_reporting.accountabilities

  build-vegetation-types-microservice:
    name: Build FLINT Reporting Vegetation Types Microservice
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/vegetation-types/
  
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build accountabilities microservice 
        run: docker build . --file Dockerfile --tag flint_reporting.vegetation-types

    
  build-vegetation-history-vegetation-types-microservice:
    name: Build FLINT Reporting Vegetation History Vegetation Types
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/vegetation-history-vegetation-types/
  
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build accountabilities microservice 
        run: docker build . --file Dockerfile --tag flint_reporting.vegetation-history-vegetation-types

  build-units-microservice:
    name: Build FLINT Reporting Units
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/units/
  
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build accountabilities microservice 
        run: docker build . --file Dockerfile --tag flint_reporting.units

  build-unit-categories-microservice:
    name: Build FLINT Reporting Unit Categories
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/services/unit-categories/

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'maven'

      - name: Build with maven 
        run: bash build.sh 

      - name: Build accountabilities microservice 
        run: docker build . --file Dockerfile --tag flint_reporting.unit-categories
