name: Reporting tool frontend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: code/client

jobs:
  build:
    name: Build the frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          npm install -g @angular/cli
          npm install

      - name: Build UI
        run: |
          bash build.sh
