name: Test action

on:
  schedule:
    - cron: "0 0 * * MON"

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]

  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install k8s
      run: |
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
        cat /etc/rancher/k3s/k3s.yaml
        mkdir -p ~/.kube
        cp /etc/rancher/k3s/k3s.yaml ~/.kube/config



    - name: Kubernetes services tests
      run: |
        cd ./code/scripts/setup/system/services/
        bash install.sh
        kubectl get po